---
- name: Create a file containing the host's IP
  hosts: localhost
  tasks:
    - name: Get the host's IP address
      shell: hostname -I
      register: host_ip

    - name: Create a file containing the IP address
      copy:
        dest: /user/bin/tmp/host_ip.txt
        state: touch
        content: "{{ host_ip.stdout }}"