- hosts: all
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: Add nginx conf
    template:                          # Replace copy for template
      src: "{{ path_to_nginx_conf }}"  # Change this line to a variable
      dest: /etc/nginx/nginx.conf
    notify: Restart nginx

  handlers:                            #  Add this line 
  - name: "Restart nginx"              #  Move
    service:                           #  the restart task to here
      name: "nginx"                    #  to 
      state: "restarted"               #  here