---
- name: Clone a Git repo
  hosts: localhost
  tasks:
  - name: Install Git
    become: yes
    apt:
      name: git
      state: present

  - name: Clone the repo
    git:
      repo: https://github.com/pelumiman/AMS-Wflow.git
      dest: /path/to/local/repo